package com.luckymall.mbg.dao;

import com.luckymall.mbg.entity.LuckyAdmin;
import com.luckymall.mbg.entity.LuckyAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LuckyAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    long countByExample(LuckyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int insert(LuckyAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int insertSelective(LuckyAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    LuckyAdmin selectOneByExample(LuckyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    LuckyAdmin selectOneByExampleSelective(@Param("example") LuckyAdminExample example, @Param("selective") LuckyAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    List<LuckyAdmin> selectByExampleSelective(@Param("example") LuckyAdminExample example, @Param("selective") LuckyAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    List<LuckyAdmin> selectByExample(LuckyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    LuckyAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    LuckyAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    LuckyAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyAdmin record, @Param("example") LuckyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyAdmin record, @Param("example") LuckyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}