package com.luckymall.mbg.dao;

import com.luckymall.mbg.entity.LuckyLog;
import com.luckymall.mbg.entity.LuckyLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LuckyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    long countByExample(LuckyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int insert(LuckyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int insertSelective(LuckyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    LuckyLog selectOneByExample(LuckyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    LuckyLog selectOneByExampleSelective(@Param("example") LuckyLogExample example, @Param("selective") LuckyLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    List<LuckyLog> selectByExampleSelective(@Param("example") LuckyLogExample example, @Param("selective") LuckyLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    List<LuckyLog> selectByExample(LuckyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    LuckyLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    LuckyLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    LuckyLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyLog record, @Param("example") LuckyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyLog record, @Param("example") LuckyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}