spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://81.71.68.124:33061/admin?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
      username: root
      password: 123456