package com.luckymall.admin.dao;

import com.luckymall.admin.entity.LuckyRole;
import com.luckymall.admin.entity.LuckyRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LuckyRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    long countByExample(LuckyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int insert(LuckyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int insertSelective(LuckyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    LuckyRole selectOneByExample(LuckyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    LuckyRole selectOneByExampleSelective(@Param("example") LuckyRoleExample example, @Param("selective") LuckyRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    List<LuckyRole> selectByExampleSelective(@Param("example") LuckyRoleExample example, @Param("selective") LuckyRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    List<LuckyRole> selectByExample(LuckyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    LuckyRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    LuckyRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    LuckyRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyRole record, @Param("example") LuckyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyRole record, @Param("example") LuckyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}