package com.luckymall.goods.dao;

import com.luckymall.goods.entity.LuckyGoodsProduct;
import com.luckymall.goods.entity.LuckyGoodsProductExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LuckyGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    long countByExample(LuckyGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int insert(LuckyGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(LuckyGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    LuckyGoodsProduct selectOneByExample(LuckyGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    LuckyGoodsProduct selectOneByExampleSelective(@Param("example") LuckyGoodsProductExample example, @Param("selective") LuckyGoodsProduct.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    List<LuckyGoodsProduct> selectByExampleSelective(@Param("example") LuckyGoodsProductExample example, @Param("selective") LuckyGoodsProduct.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    List<LuckyGoodsProduct> selectByExample(LuckyGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    LuckyGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyGoodsProduct.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    LuckyGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    LuckyGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyGoodsProduct record, @Param("example") LuckyGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyGoodsProduct record, @Param("example") LuckyGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}