package com.luckymall.goods.dao;

import com.luckymall.goods.entity.LuckyGoodsSpecification;
import com.luckymall.goods.entity.LuckyGoodsSpecificationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LuckyGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(LuckyGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int insert(LuckyGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(LuckyGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    LuckyGoodsSpecification selectOneByExample(LuckyGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    LuckyGoodsSpecification selectOneByExampleSelective(@Param("example") LuckyGoodsSpecificationExample example, @Param("selective") LuckyGoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    List<LuckyGoodsSpecification> selectByExampleSelective(@Param("example") LuckyGoodsSpecificationExample example, @Param("selective") LuckyGoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    List<LuckyGoodsSpecification> selectByExample(LuckyGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    LuckyGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyGoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    LuckyGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    LuckyGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyGoodsSpecification record, @Param("example") LuckyGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyGoodsSpecification record, @Param("example") LuckyGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}