package com.luckymall.goods.dao;

import com.luckymall.goods.entity.LuckyGoods;
import com.luckymall.goods.entity.LuckyGoodsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LuckyGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    long countByExample(LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int insert(LuckyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int insertSelective(LuckyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    LuckyGoods selectOneByExample(LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    LuckyGoods selectOneByExampleSelective(@Param("example") LuckyGoodsExample example, @Param("selective") LuckyGoods.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    LuckyGoods selectOneByExampleWithBLOBs(LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    List<LuckyGoods> selectByExampleSelective(@Param("example") LuckyGoodsExample example, @Param("selective") LuckyGoods.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    List<LuckyGoods> selectByExampleWithBLOBs(LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    List<LuckyGoods> selectByExample(LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    LuckyGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyGoods.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    LuckyGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    LuckyGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyGoods record, @Param("example") LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LuckyGoods record, @Param("example") LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyGoods record, @Param("example") LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LuckyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}