package com.luckymall.goods.dao;

import com.luckymall.goods.entity.LuckyBrand;
import com.luckymall.goods.entity.LuckyBrandExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LuckyBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    long countByExample(LuckyBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int insert(LuckyBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int insertSelective(LuckyBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    LuckyBrand selectOneByExample(LuckyBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    LuckyBrand selectOneByExampleSelective(@Param("example") LuckyBrandExample example, @Param("selective") LuckyBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    List<LuckyBrand> selectByExampleSelective(@Param("example") LuckyBrandExample example, @Param("selective") LuckyBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    List<LuckyBrand> selectByExample(LuckyBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    LuckyBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    LuckyBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    LuckyBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyBrand record, @Param("example") LuckyBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyBrand record, @Param("example") LuckyBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}