package com.luckymall.goods.dao;

import com.luckymall.goods.entity.LuckyCategory;
import com.luckymall.goods.entity.LuckyCategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LuckyCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    long countByExample(LuckyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int insert(LuckyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int insertSelective(LuckyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    LuckyCategory selectOneByExample(LuckyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    LuckyCategory selectOneByExampleSelective(@Param("example") LuckyCategoryExample example, @Param("selective") LuckyCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    List<LuckyCategory> selectByExampleSelective(@Param("example") LuckyCategoryExample example, @Param("selective") LuckyCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    List<LuckyCategory> selectByExample(LuckyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    LuckyCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    LuckyCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    LuckyCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyCategory record, @Param("example") LuckyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyCategory record, @Param("example") LuckyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}