package com.luckymall.goods.dao;

import com.luckymall.goods.entity.LuckyGoodsAttribute;
import com.luckymall.goods.entity.LuckyGoodsAttributeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LuckyGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(LuckyGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(LuckyGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int insert(LuckyGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(LuckyGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    LuckyGoodsAttribute selectOneByExample(LuckyGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    LuckyGoodsAttribute selectOneByExampleSelective(@Param("example") LuckyGoodsAttributeExample example, @Param("selective") LuckyGoodsAttribute.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    List<LuckyGoodsAttribute> selectByExampleSelective(@Param("example") LuckyGoodsAttributeExample example, @Param("selective") LuckyGoodsAttribute.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    List<LuckyGoodsAttribute> selectByExample(LuckyGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    LuckyGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LuckyGoodsAttribute.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    LuckyGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    LuckyGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LuckyGoodsAttribute record, @Param("example") LuckyGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LuckyGoodsAttribute record, @Param("example") LuckyGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LuckyGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LuckyGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LuckyGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}